### ISSUE TITLE
Unable to use Mongock5  without transactions

### ISSUE THREAD

**Issue by wuttke** [flamingock/mongock#115]
## Description

During startup of my application, I get:

`Caused by: io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.execution] : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
`

I tried to add retryWrites=false, but that did not help.

My application.properties has:

```
mongock:
  migration-scan-package: de.mesalvo.encounter.migrations
  transaction-enabled: false

```
My POM:

		<dependency>
			<groupId>io.mongock</groupId>
			<artifactId>mongock-springboot</artifactId>
			<version>5.2.1</version>
		</dependency>

		<dependency>
			<groupId>io.mongock</groupId>
			<artifactId>mongodb-reactive-driver</artifactId>
			<version>5.2.1</version>
		</dependency>

## PRIORITY

CRITICAL

### Mongock
- Mongock version 5.2.1
- Modules involved: springboot, MongoDB, reactive
- How Mongock is used: annotation approach

### Environment
- Framework and libraries versions. Spring Boot 2.6.2
- Infrastructure: local

## Steps to Reproduce

1. Just need to start the application#

## Behaviour

**Expected behavior:** Changeset to be executed

**Actual behavior:** Exception

**How often the bug happens:** 100%

## Additional context

Using this config bean:

	@Bean
	public ConnectionDriver mongockMongoConnection(MongoClient reactiveMongoClient) {
		return MongoReactiveDriver.
				withDefaultLock(reactiveMongoClient, "mesalvo_encounter");
	}

**Comment by osantana85** [comment]
Hello @wuttke , we'll take a look and let you know. Please could you confirm if you are using a standalone mongodb server or a replicaset one? Thanks.

**Comment by wuttke** [comment]
Thanks! It’s standalone. I’d suppose with replica sets it should work…

**Comment by osantana85** [comment]
Hello @wuttke , we've just released Mongock version 5.2.2 which fixed this issue. Please could you try it and let us know? Thanks.

**Comment by wuttke** [comment]
Will do, thanks

**Comment by wuttke** [comment]
Great, the exception is away and my change set is applied!

It did not auto-detect the driver, so I had to add this:

	@Bean
	public ConnectionDriver mongockMongoConnection(MongoClient reactiveMongoClient,
				   @Value("${spring.data.mongodb.database}") String databaseName) {
		return MongoReactiveDriver.
				withDefaultLock(reactiveMongoClient, databaseName);
	}

But I am unsure if this is a problem or works-as-designed. :-)

Thanks for the quick fix!

**Comment by osantana85** [comment]
Could you write the output log with the error you get? It should be auto-injected... Also you can take a look to our examples repository [here](https://github.com/mongock/mongock-examples). The "springboot-quickstart" example is the simplest and auto-configured option.

**Comment by wuttke** [comment]
I have the two dependencies mentioned above in my POM. I do not find any references to the MongoReactiveDriver except from my bean declaration. If I remove my bean declaration above, I get this exception:

```
2022-12-07 13:52:51.282 DEBUG 48180 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.mongock.driver.api.driver.ConnectionDriver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
	at de.mesalvo.encounter.MesalvoEncounterApplication.main(MesalvoEncounterApplication.java:17)

2022-12-07 13:52:51.282 ERROR 48180 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method getBuilder in io.mongock.runner.springboot.config.MongockContext required a bean of type 'io.mongock.driver.api.driver.ConnectionDriver' that could not be found.


Action:

Consider defining a bean of type 'io.mongock.driver.api.driver.ConnectionDriver' in your configuration.
```

**Comment by osantana85** [comment]
Hello @wuttke , you are right. Mongock's mongodb reactive driver does not include spring features, so it won't be injected to the spring context. You need to inject it in the same way you write above.
